name: Generate ASCII Artwork
on: push

jobs:
  ascii_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git Repo
        uses: actions/checkout@v4

      - name: Install Cowsay Program
        run: sudo apt-get install cowsay -y

      - name: Execute Cowsay CMD
        run: cowsay -f lion "Run for cover, I am a LION.. .. RAWR" > lion.txt

      - name: Test File Exists
        run: grep -i "lion" lion.txt

      - name: Read File
        run: cat lion.txt

      - name: List Repo File
        run: ls -lrat
