name: Generate ASCII Artwork
on: push

jobs:
  build_job-1:
    runs-on: ubuntu-latest
    steps:
      - name: install cowsay program
        run: sudo apt-get install cowsay -y
      
      - name: Execute cowsay command
        run: cowsay -f dragon "Run for cover, I am a DRAGON...RAWR" > dragon.txt

      - name: Upload Dragon Text file
        uses: actions/upload-artifact@v4
        with:
          name: dragon-text-file
          path: dragon.txt

  test_job-2:
    needs: build_job-1
    runs-on: ubuntu-latest

    steps:
      - name: Download Dragon Text file
        uses: actions/download-artifact@v4
        with:
          name: dragon-text-file

      - name: Test File Exists
        run: grep -i "dragon" dragon.txt
      
  deploy_job-3:
    needs: [test_job-2, build_job-1]
    runs-on: ubuntu-latest

    steps:
      - name: Download Dragon Text file
        uses: actions/download-artifact@v4
        with:
          name: dragon-text-file

      - name: Read Files
        run: cat dragon.txt

      - name: Deploy
        run: echo Deploying...
         
 
