name: Generate ASCII Artwork
on: push

jobs:
  ascii_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git Repo
        uses: actions/checkout@v4

      - name: List Repo Files
        run: ls -lart

      - name: Execute Shell Script
        run: ./ascii-script.sh
         
