name: Generate ASCII Artwork
on: push

jobs:
  build_job-1:
    runs-on: ubuntu-latest
    steps:
      - name: install cowsay program
        run: sudo apt-get install cowsay -y
      
      - name: Execute cowsay command
        run: cowsay -f dragon "Run for cover, I am a DRAGON...RAWR" > dragon.txt
      - name: sleep for 30 sec
        run: sleep 30

  test_job-2:
    needs: build_job-1
    runs-on: ubuntu-latest

    steps:
      - name: sleep for 10 sec
        run: sleep 10

      - name: Test File Exists
        run: grep -i "dragon" dragon.txt
      
  deploy_job-3:
    needs: [test_job-2, test_job-2]
    runs-on: ubuntu-latest

    steps:
      - name: Read Files
        run: cat dragon.txt

      - name: Deploy
        run: echo Deploying...
         
 
