name: Exploring if expression
on: 
  push

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

  build:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: Build
        run: echo "building..."

  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: [checkout, build]
    steps:   
      - name: Deploy
        run: echo "Deploying..."
