name: Exploring timeouts concept
on: 
  push

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

  build-deploy:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: Build
        run: echo "building..."

      - name: Deploy
        timeout-minutes: 1
        run: |
          echo "Deploying..."
          sleep 6000s  
     
