name: Exploring Variables at Job level

on: [push]

jobs:
  example-job:
    runs-on: ubuntu-latest
    env:
        JOB_VARIABLE: "Job level"
        
    steps:
      - run: echo "Job env is ${{env.JOB_VARIABLE }}"
