name: Exploring Work Flow Triggers

on: 
  workflow_dispatch: 
  
jobs:
  Work_Flow_Triggers:
    runs-on: ubuntu-latest 

    steps:
      - name: Cron Job
        run: echo "Executed Using manual Trigger"
