name: Exploring Work Flow Triggers

on: 
  workflow_dispatch: 
  
jobs:

  Build:
    runs-on: ubuntu-latest 

    steps:
      - name: Building 
        run: echo "Building Sucessfully"

  Deply:
    needs: Build
    concurrency: 
      group: Production-Deloyment
      cancel-in-progress: false
    runs-on: ubuntu-latest 

    steps:
      - name: Cron Job
        run: echo "Deployed Sucessfully"
